[package]
name = "rproxy-rs"
version = "0.1.0"
authors = ["Max Lapshin <max@maxidoors.ru>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
#tokio-tls = "0.1.1"
getopts = "0.2"

[profile.release]
lto = true
panic = 'abort'